"""Compatibility facade. Implementation lives in ``gui.shell.app``."""

from ig_orchestrator.gui.shared.helpers import (
    _BATCH_COLUMNS,
    _account_display_status,
    _batch_column_samples,
    _batch_mode_details,
    _catalog_entry_colors,
    _catalog_width_chars,
    _half_screen_geometry,
    _instagram_profile_url,
    _latest_executed_batch_name,
    _new_account_rename_parameters,
    _open_chrome_tab,
    _play_completion_sound,
    _set_ttk_enabled,
    _sort_accounts_by_username,
    _timestamp_console_text,
    _username_heading_title,
    batch_username_matches_filter,
    catalog_focus_username,
    filter_batch_accounts,
    stories_cell_text,
)
from ig_orchestrator.gui.shell.app import InstagramOrchestratorApp, launch_gui

__all__ = [
    "InstagramOrchestratorApp",
    "launch_gui",
    "_BATCH_COLUMNS",
    "_account_display_status",
    "_batch_column_samples",
    "_batch_mode_details",
    "_catalog_entry_colors",
    "_catalog_width_chars",
    "_half_screen_geometry",
    "_instagram_profile_url",
    "_latest_executed_batch_name",
    "_new_account_rename_parameters",
    "_open_chrome_tab",
    "_play_completion_sound",
    "_set_ttk_enabled",
    "_sort_accounts_by_username",
    "_timestamp_console_text",
    "_username_heading_title",
    "batch_username_matches_filter",
    "catalog_focus_username",
    "filter_batch_accounts",
    "stories_cell_text",
]
